### ISSUE TITLE
Please add this symbols and methods

### ISSUE THREAD

**Issue by joowh85** [paveldruzyak/language-rspec#18]
Please add this symbols and methods

More usages
 https://github.com/rails/rails/blob/v4.0.0/guides/source/layouts_and_rendering.md#the-status-option

Response Class	HTTP Status Code	Symbol
Informational	100	:continue
101	:switching_protocols
102	:processing
Success	200	:ok
201	:created
202	:accepted
203	:non_authoritative_information
204	:no_content
205	:reset_content
206	:partial_content
207	:multi_status
208	:already_reported
226	:im_used
Redirection	300	:multiple_choices
301	:moved_permanently
302	:found
303	:see_other
304	:not_modified
305	:use_proxy
306	:reserved
307	:temporary_redirect
308	:permanent_redirect
Client Error	400	:bad_request
401	:unauthorized
402	:payment_required
403	:forbidden
404	:not_found
405	:method_not_allowed
406	:not_acceptable
407	:proxy_authentication_required
408	:request_timeout
409	:conflict
410	:gone
411	:length_required
412	:precondition_failed
413	:request_entity_too_large
414	:request_uri_too_long
415	:unsupported_media_type
416	:requested_range_not_satisfiable
417	:expectation_failed
422	:unprocessable_entity
423	:locked
424	:failed_dependency
426	:upgrade_required
423	:precondition_required
424	:too_many_requests
426	:request_header_fields_too_large
Server Error	500	:internal_server_error
501	:not_implemented
502	:bad_gateway
503	:service_unavailable
504	:gateway_timeout
505	:http_version_not_supported
506	:variant_also_negotiates
507	:insufficient_storage
508	:loop_detected
510	:not_extended
511	:network_authentication_required

**Comment by ryansobol** [comment]
Why?

**Comment by joowh85** [comment]
I mean put this code snippets on the Autocomplete feature at Atom. 
Is not a your project?

**Comment by paveldruzyak** [comment]
I think will be better to do this in some separate plugin.
