### ISSUE TITLE
Constants don't line up with the cursor

### ISSUE THREAD

**Issue by richrace** [paveldruzyak/language-rspec#24]
Only happens when using the RSpec language: 

![typing](https://cloud.githubusercontent.com/assets/1273965/7724522/284c0ac0-feea-11e4-8f1c-4c98c60cffd8.gif)

If I change my font to different one, then back to the original one, this problem doesn't happen. Not Sure if it's an Atom problem?

**Comment by paveldruzyak** [comment]
@richrace is it still actual issue?

**Comment by richrace** [comment]
No I am not.
