### ISSUE TITLE
ruby cannot be found.

### ISSUE THREAD

**Issue by ghost** [paveldruzyak/language-rspec#32]
Hello, 

I installed your plugin on Ubuntu where I installed ruby and rails with rbenv. 
Every time if I do crtl+shift+t I see a message that ruby cannot be found..

Ruby is in the path if I looked at 
process.env.PATH and which ruby

**Comment by paveldruzyak** [comment]
Sorry, but this package don't use ruby, so looks like you got that message from other place.
