### ISSUE TITLE
syntax highlighting issue with variables named `feature`

### ISSUE THREAD

**Issue by blimmer** [paveldruzyak/language-rspec#39]
For example:

```ruby
describe 'something' do
  it 'does stuff' do
    feature = create(:something)
  end
end
```

looks like this:

<img width="409" alt="screen shot 2017-02-14 at 4 13 26 pm" src="https://cloud.githubusercontent.com/assets/630449/22953895/888d02a0-f2d0-11e6-9f3f-ce6987e57421.png">

and breaks future syntax highlighting:

```ruby
describe 'something' do
  it 'does stuff' do
    feature = create(:something)
  end

  context 'something else' do
    
  end
end
```

<img width="424" alt="screen shot 2017-02-14 at 4 14 13 pm" src="https://cloud.githubusercontent.com/assets/630449/22953916/a51ca5ba-f2d0-11e6-9d61-c13f57aae4dc.png">

**Comment by hayesr** [comment]
Ran into this too. Given the choice I wouldn't use feature as a local var name, but I'm working on a legacy code base that uses it.

`feature` by itself will break highlighting unless the line ends with `do`

![screen shot 2017-03-01 at 2 19 45 pm](https://cloud.githubusercontent.com/assets/39493/23484149/a666ba8a-fe8a-11e6-81c2-961f440069b3.png)

![screen shot 2017-03-01 at 2 23 13 pm](https://cloud.githubusercontent.com/assets/39493/23484153/aa95470c-fe8a-11e6-9bcd-33f9fd948af8.png)

**Comment by blimmer** [comment]
Thanks!
