### ISSUE TITLE
Deprecated calls - Arguments to path.basename must be strings

### ISSUE THREAD

**Issue by dphilpot** [paveldruzyak/language-rspec#44]
Hi,

i recently get some deprecation warnings, maybe you could fix them?

`Arguments to path.basename must be strings

path.basename - /Applications/Atom.app/Contents/Resources/app.asar/src/electron-shims.js:31:10
Object._isRspecFile - /Users/dphilpot/.atom/packages/language-rspec-plus/lib/language-rspec.coffee:27:14
<unknown> - /Users/dphilpot/.atom/packages/language-rspec-plus/lib/language-rspec.coffee:11:22
Workspace.observeTextEditors - /Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:305:53
Object.activate - /Users/dphilpot/.atom/packages/language-rspec-plus/lib/language-rspec.coffee:8:29
Package.activateNow - /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:218:19`

**Comment by paveldruzyak** [comment]
@dphilpot which version of package you use?

**Comment by dphilpot** [comment]
Hi @paveldruzyak i'm using version 0.6.2 in combination with language-rspec-plus 0.1.1

**Comment by paveldruzyak** [comment]
@dphilpot oh, I see.  You got this warning from other package: /Users/dphilpot/.atom/packages/**language-rspec-plus**
