### ISSUE TITLE
Add setting for preferred quotes

### ISSUE THREAD

**Issue by exalted** [paveldruzyak/language-rspec#9]
Could you possibly add a setting where one could prefer, maybe, single quotes over double quotes when autocompleting?

I find myself replacing double quotes with single quotes all the time, which is a bit annoying to me.

Thank you,

**Comment by exalted** [comment]
Any updates here please? Thanks!

**Comment by paveldruzyak** [comment]
Sorry, but no.

**Comment by exalted** [comment]
@paveldruzyak sure, no pressure... Would you rather prefer we close this and re-open again if comes up in the future, or?

**Comment by paveldruzyak** [comment]
ok

**Comment by darrenterhune** [comment]
Reopen our team always uses double quotes as does rubocop now 😄 let me know if I can help.

**Comment by pauldruziak** [comment]
@darrenterhune above I shared a link that can help to implement this feature
